// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmicOVfWvnYO161Na_tpVS84OvpDKVsXQ',
    appId: '1:26393283659:web:f32f400388f3a0e97e11ce',
    messagingSenderId: '26393283659',
    projectId: 'student-commute-139f2',
    authDomain: 'student-commute-139f2.firebaseapp.com',
    storageBucket: 'student-commute-139f2.appspot.com',
    measurementId: 'G-L5Y0PVM80S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9ZxYt3F2KunNDFsQjeAXE0xUjc2YKlr8',
    appId: '1:26393283659:android:9cca115db1b1fee07e11ce',
    messagingSenderId: '26393283659',
    projectId: 'student-commute-139f2',
    storageBucket: 'student-commute-139f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDINJr-MGOSslLIC1r5HJtHpbOfVoj2JbA',
    appId: '1:26393283659:ios:692a71227008cf727e11ce',
    messagingSenderId: '26393283659',
    projectId: 'student-commute-139f2',
    storageBucket: 'student-commute-139f2.appspot.com',
    iosBundleId: 'com.example.studentCommute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDINJr-MGOSslLIC1r5HJtHpbOfVoj2JbA',
    appId: '1:26393283659:ios:136df6515e1bfa5b7e11ce',
    messagingSenderId: '26393283659',
    projectId: 'student-commute-139f2',
    storageBucket: 'student-commute-139f2.appspot.com',
    iosBundleId: 'com.example.studentCommute.RunnerTests',
  );
}
